# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20170620_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='job',
            field=models.CharField(default='', max_length=50),
        ),
    ]
