language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements.pip
# command to run tests

env:
  - SECRET_KEY='mashedpotatoes' DATABASE_NAME='test_db' DATABASE_USER='postgres' DATABASE_HOST="127.0.0.1" DATABASE_PASSWORD=''

services:
  - postgresql

before_script:
  - psql -c "create database test_db;" -U postgres

script: 
  - python django_imager/manage.py migrate
  - python django_imager/manage.py test django_imager