# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0002_album_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(null=True, upload_to='user_images'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='imager_images.Photo'),
        ),
    ]
