# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0003_auto_20170625_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='published',
            field=models.CharField(choices=[('PB', 'public'), ('PV', 'private'), ('SH', 'shared')], default='PV', max_length=2),
        ),
        migrations.AddField(
            model_name='photo',
            name='published',
            field=models.CharField(choices=[('PB', 'public'), ('PV', 'private'), ('SH', 'shared')], default='PV', max_length=2),
        ),
    ]
