# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0004_auto_20170625_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(default='', related_name='albums', to='imager_images.Photo'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='imager_images.Photo'),
        ),
        migrations.AlterField(
            model_name='album',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='date_published',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_published',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
