# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0006_auto_20170626_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='imager_images.Photo'),
        ),
    ]
